version: '3'

services:
  jupyter-server:
    image: sunlab/easypy:latest
    ports:
      - 8888:8888
    restart: always
    volumes:
      - ./data:/work/data
    environment:
      - CONTAINER=docker
